imports:
    - { resource: "services/form.yml" }

services:
    _defaults:
        public: true

    coreshop.money_formatter:
        class: CoreShop\Bundle\MoneyBundle\Formatter\MoneyFormatter

    coreshop.twig.extension.money:
        class: CoreShop\Bundle\MoneyBundle\Twig\FormatMoneyExtension
        public: false
        arguments:
            - '@coreshop.templating.helper.format_money'
        tags:
            - { name: twig.extension }

    coreshop.templating.helper.format_money:
        class: CoreShop\Bundle\MoneyBundle\Templating\Helper\FormatMoneyHelper
        lazy: true
        arguments:
            - '@coreshop.money_formatter'
        tags:
            - { name: templating.helper, alias: coreshop_format_money }