services:
    _defaults:
        public: true

    coreshop.form.type.money:
        class: CoreShop\Bundle\MoneyBundle\Form\Type\MoneyType
        arguments:
            - '%coreshop.currency.decimal_factor%'
        tags:
            - { name: form.type }
